In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [14]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [17]:
np.arange(0,20,2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr2.ndim

2

In [24]:
arr2.size

10

In [25]:
arr2.dtype

dtype('int64')

In [26]:
arr2.itemsize

8

In [29]:
arr2=np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [30]:
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [31]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
print(arr[1][2])
print(arr[0:2,2:])

7
[[3 4]
 [7 8]]


In [44]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [49]:
mean=np.mean(arr1)
print(mean)
stddev=np.std(arr1)
print(stddev)

normal=(arr1-mean)/stddev

print(normal)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(data)

mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

stddev=np.std(data)
print(stddev)

variance=np.var(data)
print(variance)

[ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5
2.8722813232690143
8.25
